server:
  port: 13000
spring:
  application:
    name: mall-product
  r2dbc:
    url: r2dbcs:mysql://localhost:3306/mall_pms?serverZoneId=Japan&useUnicode=true
    username: root
    password: root
    pool:
      initial-size: 5
      max-life-time: 5m
      max-idle-time: 5m
      max-size: 20
  thymeleaf:
    cache: false
  redis:
    host: localhost
    port: 6379
    timeout: 150000
    lettuce:
      pool:
        max-active: 30
        max-wait: 2
        max-idle: 10
        min-idle: 0
logging:
  level:
    org.springframework.r2dbc: debug
