server:
  port: 13000
spring:
  application:
    name: mall-product
  r2dbc:
    url: r2dbcs:mysql://localhost:3306/mall_pms?serverZoneId=Japan&useUnicode=true
    username: root
    password: root
    pool:
      initial-size: 5
      max-life-time: 5m
      max-idle-time: 5m
      max-size: 20
  thymeleaf:
    cache: true
logging:
  level:
    org.springframework.r2dbc: debug
