server:
  port: 1000
spring:
  application:
    name: mall-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: mall-coupon
          uri: lb://mall-coupon
          predicates:
            - Path=/coupon/**

        - id: mall-member
          uri: lb://mall-member
          predicates:
            - Path=/member/**

        - id: mall-order
          uri: lb://mall-order
          predicates:
            - Path=/order/**

        - id: mall-product
          uri: lb://mall-product
          predicates:
            - Path=/product/**

        - id: mall-ware
          uri: lb://mall-ware
          predicates:
            - Path=/ware/**

        - id: mall-admin
          uri: lb://mall-admin
          predicates:
            - Path=/admin/**

        - id: mall-third-party
          uri: lb://mall-third-party
          predicates:
            - Path=/third-party/**

        - id: mall-search
          uri: lb://mall-search
          predicates:
            - Path=/search/**

        - id: host-search
          uri: lb://mall-product
          predicates:
            - Host=chiwamall.com,item.chiwamall.com

        - id: host-product
          uri: lb://mall-search
          predicates:
            - Host=search.chiwamall.com

        - id: host-auth
          uri: lb://mall-security
          predicates:
            - Host=auth.chiwamall.com

        - id: host-cart
          uri: lb://mall-cart
          predicates:
            - Host=cart.chiwamall.com
