server:
  port: 10000
spring:
  application:
    name: mall-coupon
  r2dbc:
    url: r2dbcs:mysql://localhost:3306/mall_sms?serverZoneId=Japan&useUnicode=true
    username: root
    password: root
    pool:
      initial-size: 5
      max-life-time: 5m
      max-idle-time: 5m
      max-size: 20
logging:
  level:
    org.springframework.r2dbc: debug
